---
title: "bigram code"
author: "Yaqin Li (yl3578)"
date: "2017年2月2日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE,message=FALSE}
if(!require(devtools)) {
  install.packages('devtools')
}
library(devtools)
devtools::install_github('thomasp85/ggforce',force=TRUE)
devtools::install_github('thomasp85/ggraph',force=TRUE)

library(ggraph)
library(igraph)
```

```{r,echo=FALSE}
count_bigrams <- function(dataset) {
  dataset %>%
    unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
    separate(bigram, c("word1", "word2"), sep = " ") %>%
    filter(!word1 %in% stop_words$word,
           !word2 %in% stop_words$word) %>%
    count(word1, word2, sort = TRUE)
}

visualize_bigrams <- function(bigrams) {
  set.seed(2016)
  a <- grid::arrow(type = "closed", length = unit(.15, "inches"))
  
  bigrams %>%
    graph_from_data_frame() %>%
    ggraph(layout = "fr") +
    geom_edge_link(aes(edge_alpha = n), show.legend = FALSE, arrow = a) +
    geom_node_point(color = "lightblue", size = 5) +
    geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
    theme_void()
}

res_bigrams <- docs.res %>%
  count_bigrams()
head(res_bigrams)
res_bigrams %>%
  filter(n > 3,
         !str_detect(word1, "\\d"),
         !str_detect(word2, "\\d")) %>%
  visualize_bigrams()


nres_bigrams <- docs.nres %>%
  count_bigrams()
head(nres_bigrams)
nres_bigrams %>%
  filter(n > 6,
         !str_detect(word1, "\\d"),
         !str_detect(word2, "\\d")) %>%
  visualize_bigrams()


```